# render.yaml — Streamlit deployment configuration
services:
  - type: web
    name: mlb-webscraping-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard/app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
